### ISSUE TITLE
Circular progress view moves to top of screen.

### ISSUE THREAD

**Issue by anirudh-24** [OrangeGangsters/SwipyRefreshLayout#10]
I don't know if anyone is facing this issue or not.But when i use swiping in both direction the top one works fine but as soon as i pull from bottom the circular progress comes from bottom of the screen then moves to the top of the screen and fades away in a flash.
After this happens another circular progress comes from bottom and then works fine.

I'm using it with recycler view.

Device htc one x.
Android - 4.2.2

**Comment by donadev** [comment]
This is the same issue I'm facing with my phone (Android 4.3)

**Comment by oliveeyay** [comment]
Never saw it. If you can come with a fix, don't hesitate to do a pull request :)

**Comment by caijiangyang** [comment]
The same issue while using recycler view
