### ISSUE TITLE
Support setProgressBackgroundColorSchemeResource Method

### ISSUE THREAD

**Issue by grote** [OrangeGangsters/SwipyRefreshLayout#15]
Currently, there's no way to set the colour of the progress disc which is particularly bad for dark themes.

Therefore, it would be great, if you could implement the [setProgressBackgroundColorSchemeResource](https://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout.html#setProgressBackgroundColorSchemeResource%28int%29) method like the official SwipeRefreshLayout does.

**Comment by oliveeyay** [comment]
You can do a pull request for that matter, we would gladly merge it if the code is nice.
