### ISSUE TITLE
Swipe to Refresh gets activated when scrolled to end of Recycler view and Scrolling up

### ISSUE THREAD

**Issue by stripathi669** [OrangeGangsters/SwipyRefreshLayout#16]
I have a Relative layout that contains a Framelayout and Linearlayout. The framelayout contains Recycler view and Recycler Header. A swipe to refresh layout encloses all of this.

Now my problem is: When I scroll to bottom of recycler view, and start scrolling up, Swipe to Refresh gets activated instead of Recycler view scrolling up. If I remove your wonderful Pull to Refresh, everything works fine (except the part that I now won't this cool pull to refresh)

What possibly could be going wrong ?

**Comment by adin234** [comment]
same problem here. you have solved this one? @stripathi669

**Comment by stripathi669** [comment]
Yes @adin234 .

Set a onScrollListener. Compute Scroll Y, and disable pull to refresh if it is not near the top, and enable otherwise.

I understand that it might not be that much efficient. But it works. Do you need a sample code?

**Comment by adin234** [comment]
@stripathi669 i am just using a simple ScrollView in my layout, you think it will work?

**Comment by stripathi669** [comment]
Yes. The principal is same. You have to disable swipe to refresh when you're not near the top.

**Comment by adin234** [comment]
this might come in handy for people who had problems like this

``` java
//assuming you have the ScrollView saved in the variable scrollView

ViewTreeObserver.OnScrollChangedListener listener;

listener = new ViewTreeObserver.OnScrollChangedListener() {

            @Override
            public void onScrollChanged() {
                int scrollY = scrollView.getScrollY();

                if (scrollY < 50) { //threshold
                    aActivity.getPullToRefresh().setEnabled(true);
                } else {
                    aActivity.getPullToRefresh().setEnabled(false);
                }
            }
        };

scrollView.getViewTreeObserver().addOnScrollChangedListener(listener);
```

**Comment by Shruti1310** [comment]
One more solution is , instead of Recycler/List view Just use NestedScrollView , this problem wouldn't arrise at all.
