### ISSUE TITLE
The circular indicator does not show up while dragging when direction=top

### ISSUE THREAD

**Issue by realaboo** [OrangeGangsters/SwipyRefreshLayout#2]
While dragging down the inside list view, the circular indicator does not show up. Upon release it comes down into sight and start spinning and triggers OnRefreshListener.onRefresh().

When setting direction=bottom it works as expected: the indicator show up immediately when the dragging starts.

This can be reproduced using the sample app along with the lib.

**Comment by realaboo** [comment]
Well, I've found the bug and proposed a PR for it.

**Comment by oliveeyay** [comment]
Hello @realaboo 

I close this issue as we are discussing it in the pull request.

Thanks again.

Cheers,

Olivier
