### ISSUE TITLE
Is itpossible to add SwipyRefreshLayout inside SwipyRefreshLayout ?

### ISSUE THREAD

**Issue by AkshayGangurde** [OrangeGangsters/SwipyRefreshLayout#22]
Hi,
As per my application requirement I need to add two `SwipyRefreshLayout` in one activity. One for `ScrollView` and another for the `ListView` present inside the `ScrollView`.
I know its not good practice to use `ListView` inside `ScrollView` but its my need.
For `ScrollView` I'm using pull down(Direction TOP as per library) which is done and for `Listview`I need pull up(Direction Bottom as per library) which I'm not able to implement.

**Comment by oliveeyay** [comment]
Not advised, but you can probably trick a little the system.
I guess it would be the same thing as adding a ListView inside a ScrollView for instance (you can find a lot of tutorial on how to do that and adapt it to your problem).
