### ISSUE TITLE
swipe to add more from bottom is invalidate

### ISSUE THREAD

**Issue by tyronewj** [OrangeGangsters/SwipyRefreshLayout#25]
Hi, thank for this nice library. when I use swipyrefreshlayout in my activity, and i hava add header and footer, the construct like this:
|--linearlayout start
   |--header
   |-- swipyrefreshlayout start
        |--listview
   |---swipyrefreshlayout end
   |--footer
|--linearlayout end
when i want to add more info use swipyrefreshlayout from the bottom , the  MaterialProgressDrawable stuck there, and the method onRefresh() doesn't work.how can I solve it, thank you .

![screenshot_2015-09-03-10-15-50 1](https://cloud.githubusercontent.com/assets/161213/9649252/e85a102c-5224-11e5-9965-d638c5297ce3.png)

**Comment by oliveeyay** [comment]
Have you checked on the example app how it is used?
I think there is a timeout, depending on how you use the library you can break this.
