### ISSUE TITLE
Attribute name conflict with another library 

### ISSUE THREAD

**Issue by yeshuamayen** [OrangeGangsters/SwipyRefreshLayout#27]
I'm having an issue with the attribute "direction"
Gradle report following error:
`Attribute "direction" has already been defined`

Please consider using your custom and possibly unique prefix for all custom attributes. The comonly used standard is to use first characters of your library name:
`direction -> srldirection`

Thanks!

Edit: The conflict is with the library of [Mapbox](https://www.mapbox.com/android-sdk/)

**Comment by encku** [comment]
Good point.

**Comment by oliveeyay** [comment]
Good point.
Will be done in your pull request (see #28)

Thank you in advance.

Cheers,

Olivier
