### ISSUE TITLE
Will you support setProgressViewOffset ?

### ISSUE THREAD

**Issue by nectarine** [OrangeGangsters/SwipyRefreshLayout#30]
A original SwipeRefreshLayout supports setProgressViewOffset which is commented in your library.
Do you have any plan to support it :)?

**Comment by encku** [comment]
You can fork this library and change it how you want :)

**Comment by oliveeyay** [comment]
@nectarine
I don't have the time to update the library, but if you want, you can add the support and do a pull request.
I'll review it when I can :)

Cheers,

Olivier
