### ISSUE TITLE
setRefreshing(true) after onCreate is not working

### ISSUE THREAD

**Issue by maniacs-engineerica** [OrangeGangsters/SwipyRefreshLayout#34]
I am trying to make an http connection immediately after activity onCreate to show my data. While the request is processing I want to show the refreshing in true, but it doest work at this moment. How to solve that?

You can try with your example adding a "mSwipyRefreshLayout.setRefreshing(true);" in initLayout() method on MainActivity class.

Thanks!

**Comment by maniacs-engineerica** [comment]
I found the reason of this. We have to wait until SwipyRefreshLayout executes onMeasure method.

**Comment by oliveeyay** [comment]
Yes you probably have to wait for the component to be init.
You can post a runnable on the view too.

**Comment by IslamSalah** [comment]
Posting a runnable 👍 
```
mSwipeRl.post(() -> mSwipeRl.setRefreshing(true));
```
