### ISSUE TITLE
No CLassFound

### ISSUE THREAD

**Issue by nishanthvasu** [OrangeGangsters/SwipyRefreshLayout#49]
Example Code is Working Perfectly. But when i integrate into my code it throws error like this,And also i cant find any class named databinding.

Error:(35, 65) error: package com.orangegangsters.github.swiperefreshlayout.databinding does not exist

**Comment by oliveeyay** [comment]
Hello @nishanthvasu 

Is databinding enabled in your project?
Check out how to enable it, and check how our example app build.gradle is architectured?

Maybe that'll fix it?

Cheers,

Olivier
