### ISSUE TITLE
Issues when using within a NestedScrollView

### ISSUE THREAD

**Issue by grote** [OrangeGangsters/SwipyRefreshLayout#50]
RecyclerViews can now be used with `height="wrap_content"` within a NestedScrollView to scroll the entire layout. Unfortunately, this doesn't work when the RecyclerView is within a SwipyRefreshLayout. Looks like the height calculation breaks and is 0.

Here's an example:

``` xml
<android.support.v4.widget.NestedScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <android.support.v7.widget.RecyclerView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout>

</android.support.v4.widget.NestedScrollView>
```

**Comment by oliveeyay** [comment]
Hello @grote 

Unfortunately the SwipyRefreshLayout is not meant to be used that way yet.
If you find a solution, don't hesitate to do a pull request.

Cheers,

Olivier

**Comment by johnernest02** [comment]
Did you find a way around this?

**Comment by grote** [comment]
No, unfortunately not. Would still be interested in solutions/workarounds.
