### ISSUE TITLE
pull from bottom is too hard to refresh，can you tell me how to edit it  thanks

### ISSUE THREAD

**Issue by heiyeliuying** [OrangeGangsters/SwipyRefreshLayout#51]
I has used SwipyRefreshLayout in my project, and find a little problem .It's hard to start the refresh when i pull from bottom. Do you have some issues for me ?thanks anyway.

**Comment by oliveeyay** [comment]
Hello @heiyeliuying 
I did not notice it. I guess you can play with the indices (the first numbers in the class) to see if that improves your scroll?

Cheers

**Comment by fxpage** [comment]
@olivierg13 thanks for this useful library.
Is there any way to change REFRESH_TRIGGER_DISTANCE variable?
