### ISSUE TITLE
Hi, i use it SwipyRefreshLayout inside scrollview but it not show  when i run project!

### ISSUE THREAD

**Issue by lephuhung** [OrangeGangsters/SwipyRefreshLayout#56]
i use library in scrollview , but it not show in preview tab. when i run, the recycleview inside SwipyRefreshLayout, but when i run project, the recycleview not show. Can you help me,Thank you

**Comment by oliveeyay** [comment]
Hello @lephuhung 

You might have a problem with you RecycleView direcly. I don't think it's a problem with the RefreshLayout. Try to follow the tutorial to create a RecycleView and then add the RefreshLayout at the end when your list is working.

Cheers

**Comment by lephuhung** [comment]
Thank for answering my question. I have found solution. I very like your lib

Vào Thứ Sáu, ngày 07 tháng 10 năm 2016, Olivier Goutay <
notifications@github.com> đã viết:
