### ISSUE TITLE
Refresh Layout return to First item position 

### ISSUE THREAD

**Issue by AbodAndroid** [OrangeGangsters/SwipyRefreshLayout#58]
Hello , after i making bottom refreshing , and add  item to my list .I want continue scrolling down from last item, but after refresh the layout return to first item position

**Comment by oliveeyay** [comment]
Hello @AbodAndroid 

I'm not sure it's the role of the RefreshLayout to handle that, or at least it's not directly supported.
Normally you can append cells at the end/beginning of the ListView without reloading it. Google it.

Cheers
