### ISSUE TITLE
Not work with RecyclerView

### ISSUE THREAD

**Issue by chihung93** [OrangeGangsters/SwipyRefreshLayout#61]
SwipyRefreshLayout shows though not until the end of the list

**Comment by oliveeyay** [comment]
Hello @trihung93 

Something must be wrong in your adapter, it works fine with me.

Cheers,

Olivier

**Comment by ghost** [comment]
@olivierg13 It seems mTouchSlop changes when user using listView or recyclerView.
So it's working well with listView, but have to pull far away when using recyclerView.

Please let me know your opinion and when can you fix this problem.

**Comment by chihung93** [comment]
it's not working .
My project use Recyclerview : 
https://github.com/trihung93/SwipyRefreshLayout

**Comment by Hitexroid** [comment]
it works fine with me. 🥇

**Comment by chihung93** [comment]
@Hitexroid Are you run my project? Or just example from OrangeGangsters

**Comment by Hitexroid** [comment]
no , i see your project
your problem is in activity_main.xml

remove FrameLayout :)

**Comment by chihung93** [comment]
SwipyRefreshLayout extends ViewGroup, But I must use FrameLayout for multiple View in there.
Thank you so much @Hitexroid

**Comment by Hitexroid** [comment]
Child of Swipy must be RecyclerView FrameLayout or etc... not support !
and it's a bug .
