### ISSUE TITLE
Can we make it "more sensitive"

### ISSUE THREAD

**Issue by miroslavign** [OrangeGangsters/SwipyRefreshLayout#66]
Like, in order to trigger the event, adjust sensitivity to "need less swipe motion" ?

**Comment by miroslavign** [comment]
My guess is (until I really try it out) to 
expose 
`private static final int REFRESH_TRIGGER_DISTANCE = 120;`

**Comment by miroslavign** [comment]
Actually, I found it easier to fiddle with 
`    private static final float MAX_SWIPE_DISTANCE_FACTOR = .1f;`
I will implement it and create a PR one of these days

**Comment by ManoR88** [comment]
Hello miroslavign can you please say how to use it with this one.
