### ISSUE TITLE
Swipe Bottom Issue

### ISSUE THREAD

**Issue by githubfan12221030** [OrangeGangsters/SwipyRefreshLayout#7]
Hello!
Thanks for your nice layout. I have added this library in my project.
It looks perfect.
But I have one issue.
When swipe from top to bottom, it works perfect.
but when from bottom to top,  the circle button fly away to the top when swiping, and after the touch end, circle button is showing, 
can you please fix this issue?
Thanks.

**Comment by oliveeyay** [comment]
Hello!

Are you using the last version? (1.2.0)

Cheers,
Olivier

**Comment by githubfan12221030** [comment]
Hello! 
Yes.
I have used gradle dependency, exactly 1.2.0
Here demo app has also that issue.

Thanks.

**Comment by githubfan12221030** [comment]
Hello!
Please check this.
https://bitbucket.org/andreyice/swiperefreshlayoutbottom/src

Although this has only bottom direction, but your problem is fixed.
Cheers.

**Comment by oliveeyay** [comment]
Hello @githubfan12221030 

We don't share exactly the same source code with the other repo.
I'm gonna see on Monday what the problem is and if I can reproduce.

I keep you in touch.

Cheers,

Olivier

**Comment by oliveeyay** [comment]
Hello @githubfan12221030 

I can't reproduce your issue (using a Nexus 5 and a Galaxy S4).
What is your device? Can you describe me the exact steps that lead to the issue?

Thank you in advance.

Cheers,

Olivier

**Comment by oliveeyay** [comment]
@githubfan12221030 
Any news concerning this issue? Did you see my previous messages?

**Comment by iceeyes01** [comment]
This problem also comes to me. I test your last version lib and demo in my device SUMSUNG NOTE2 & MEIZU MX3. Both of them show up the problem.

**Comment by iceeyes01** [comment]
My NOTE2 is using MIUI rom.

**Comment by leehankyeol** [comment]
I'm not pretty sure but I observed this error in my app.
I think it's related to the other elements other than ListView in children.

For example,

```
<SwipyRefreshLayout>
    <RelativeLayout>
        <ListView></ListView>
        <SomeElseView></SomeElseView>
    </RelativeLayout>
</SwipyRefreshLayout>
```

Also in that situation, I found it hard to determine when the `SwipyRefreshLayout` should be enabled. For example, I've been using the following condition to enable `SwipeRefreshLayout` in the same situation.

```
@Override
public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount) {
    boolean enable = false;
    if(mListView != null && mListView.getChildCount() > 0){
        // check if the first item of the list is visible
        boolean firstItemVisible = mListView.getFirstVisiblePosition() == 0;
        // check if the top of the first item is visible
        boolean topOfFirstItemVisible = mListView.getChildAt(0).getTop() == 0;
        // enabling or disabling the refresh layout
        enable = firstItemVisible && topOfFirstItemVisible;
    }
    mSwipeView.setEnabled(enable);
}
```
