### ISSUE TITLE
The height of MaterialProgressDrawable

### ISSUE THREAD

**Issue by enginebai** [OrangeGangsters/SwipyRefreshLayout#8]
Hi, thank for this nice library. Is it possible to set the y of `MaterialProgressDrawable`?? My `MaterialProgressDrawable` at bottom is too low to see the animation well.

This is my screen.
![device-2015-03-03-173542](https://cloud.githubusercontent.com/assets/3387462/6459710/15d3a08e-c1cc-11e4-876a-703656d25550.png)

**Comment by StoyanD** [comment]
Thanks. I think changing the height would be overkill. Could you just give your listview some paddingBottom? Let me know

**Comment by enginebai** [comment]
I set the `paddingBottom` to my `RecyclerView`, but the y of `MaterialProgressDrawable` does not change at all.

![device-2015-03-04-093156](https://cloud.githubusercontent.com/assets/3387462/6476527/01533b0c-c252-11e4-95c9-05b8aaf6830c.png)

**Comment by enginebai** [comment]
By the way, I use `RecyclerView` instead of traditional `ListView`.

**Comment by oliveeyay** [comment]
You should set the padding directly to the "SwipyRefreshLayout", as it is the one that contains the spinner.

Cheers,

Olivier
