### ISSUE TITLE
Swiping From Bottom

### ISSUE THREAD

**Issue by HamzehSoboh** [OrangeGangsters/SwipyRefreshLayout#9]
When I swipe my list from the bottom then the circular progress view stick at the bottom of the list, and when I release it, it moves up a little bit. It will be perfect if it would have the same behavior as the top direction.

I'm testing on Sony Z3 device with android 4.4.4 OS version.
Thanks.

**Comment by oliveeyay** [comment]
Yes I figured that also, but it is kind of hard to dig into.
Maybe in a next release or if someone is able to do a Pull Request that handles that!

Cheers,

Olivier

**Comment by darktimes** [comment]
Just did a pull request, that works for me. Figured out, that offset calculation doesn' work as intended.

**Comment by oliveeyay** [comment]
Did not see you pull request? Or did I merge it already? I dont remember xD
